# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 3.0.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "3.0.0")
   message(FATAL_ERROR "CMake >= 3.0.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 3.0.0...4.1)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS IfcOpenShell::OpenCASCADE_INTERFACE IfcOpenShell::IFCOPENSHELL_RocksDB IfcOpenShell::IfcParse IfcOpenShell::geometry_kernel_opencascade IfcOpenShell::geometry_serializer IfcOpenShell::geometry_serializer_ifc2x3 IfcOpenShell::geometry_serializer_ifc4 IfcOpenShell::geometry_serializer_ifc4x3_add2 IfcOpenShell::geometry_mapping_ifc2x3 IfcOpenShell::geometry_mapping_ifc4 IfcOpenShell::geometry_mapping_ifc4x3_add2 IfcOpenShell::IfcGeom IfcOpenShell::IfcConvert IfcOpenShell::IfcGeomServer)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target IfcOpenShell::OpenCASCADE_INTERFACE
add_library(IfcOpenShell::OpenCASCADE_INTERFACE INTERFACE IMPORTED)

set_target_properties(IfcOpenShell::OpenCASCADE_INTERFACE PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:\\IfcOpenShell\\_deps-vs2026-x64-v142-installed\\opencascade-8.0.0-vc14-64-pch-with-debug-combined\\opencascade-8.0.0-vc14-64\\inc"
  INTERFACE_LINK_DIRECTORIES "D:/IfcOpenShell/_deps-vs2026-x64-v142-installed/opencascade-8.0.0-vc14-64-pch-with-debug-combined/opencascade-8.0.0-vc14-64/win64/vc14/lib"
  INTERFACE_LINK_LIBRARIES "\$<\$<NOT:\$<CONFIG:DEBUG>>:TKernel>;\$<\$<CONFIG:DEBUG>:TKerneld>;\$<\$<NOT:\$<CONFIG:DEBUG>>:TKMath>;\$<\$<CONFIG:DEBUG>:TKMathd>;\$<\$<NOT:\$<CONFIG:DEBUG>>:TKBRep>;\$<\$<CONFIG:DEBUG>:TKBRepd>;\$<\$<NOT:\$<CONFIG:DEBUG>>:TKGeomBase>;\$<\$<CONFIG:DEBUG>:TKGeomBased>;\$<\$<NOT:\$<CONFIG:DEBUG>>:TKGeomAlgo>;\$<\$<CONFIG:DEBUG>:TKGeomAlgod>;\$<\$<NOT:\$<CONFIG:DEBUG>>:TKG3d>;\$<\$<CONFIG:DEBUG>:TKG3dd>;\$<\$<NOT:\$<CONFIG:DEBUG>>:TKG2d>;\$<\$<CONFIG:DEBUG>:TKG2dd>;\$<\$<NOT:\$<CONFIG:DEBUG>>:TKShHealing>;\$<\$<CONFIG:DEBUG>:TKShHealingd>;\$<\$<NOT:\$<CONFIG:DEBUG>>:TKTopAlgo>;\$<\$<CONFIG:DEBUG>:TKTopAlgod>;\$<\$<NOT:\$<CONFIG:DEBUG>>:TKMesh>;\$<\$<CONFIG:DEBUG>:TKMeshd>;\$<\$<NOT:\$<CONFIG:DEBUG>>:TKPrim>;\$<\$<CONFIG:DEBUG>:TKPrimd>;\$<\$<NOT:\$<CONFIG:DEBUG>>:TKBool>;\$<\$<CONFIG:DEBUG>:TKBoold>;\$<\$<NOT:\$<CONFIG:DEBUG>>:TKBO>;\$<\$<CONFIG:DEBUG>:TKBOd>;\$<\$<NOT:\$<CONFIG:DEBUG>>:TKFillet>;\$<\$<CONFIG:DEBUG>:TKFilletd>;\$<\$<NOT:\$<CONFIG:DEBUG>>:TKXSBase>;\$<\$<CONFIG:DEBUG>:TKXSBased>;\$<\$<NOT:\$<CONFIG:DEBUG>>:TKOffset>;\$<\$<CONFIG:DEBUG>:TKOffsetd>;\$<\$<NOT:\$<CONFIG:DEBUG>>:TKHLR>;\$<\$<CONFIG:DEBUG>:TKHLRd>;\$<\$<NOT:\$<CONFIG:DEBUG>>:TKBin>;\$<\$<CONFIG:DEBUG>:TKBind>;\$<\$<NOT:\$<CONFIG:DEBUG>>:TKDESTEP>;\$<\$<CONFIG:DEBUG>:TKDESTEPd>;\$<\$<NOT:\$<CONFIG:DEBUG>>:TKDEIGES>;\$<\$<CONFIG:DEBUG>:TKDEIGESd>;ws2_32.lib"
)

# Create imported target IfcOpenShell::IFCOPENSHELL_RocksDB
add_library(IfcOpenShell::IFCOPENSHELL_RocksDB INTERFACE IMPORTED)

set_target_properties(IfcOpenShell::IFCOPENSHELL_RocksDB PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "IFOPSH_WITH_ROCKSDB"
  INTERFACE_LINK_LIBRARIES "RocksDB::rocksdb;zstd::libzstd_static"
)

# Create imported target IfcOpenShell::IfcParse
add_library(IfcOpenShell::IfcParse SHARED IMPORTED)

set_target_properties(IfcOpenShell::IfcParse PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "HAS_SCHEMA_2x3;HAS_SCHEMA_4;HAS_SCHEMA_4x3_add2;SCHEMA_SEQ=(2x3)(4)(4x3_add2);WITH_IFCXML"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "LibXml2::LibXml2;Boost::system;Boost::program_options;Boost::regex;Boost::thread;Boost::date_time;Boost::iostreams;bcrypt.lib;IfcOpenShell::IFCOPENSHELL_RocksDB"
)

# Create imported target IfcOpenShell::geometry_kernel_opencascade
add_library(IfcOpenShell::geometry_kernel_opencascade SHARED IMPORTED)

set_target_properties(IfcOpenShell::geometry_kernel_opencascade PROPERTIES
  INTERFACE_LINK_LIBRARIES "IfcOpenShell::IfcGeom;Eigen3::Eigen;IfcOpenShell::OpenCASCADE_INTERFACE"
)

# Create imported target IfcOpenShell::geometry_serializer
add_library(IfcOpenShell::geometry_serializer SHARED IMPORTED)

set_target_properties(IfcOpenShell::geometry_serializer PROPERTIES
  INTERFACE_LINK_LIBRARIES "IfcOpenShell::geometry_serializer_ifc2x3;IfcOpenShell::geometry_serializer_ifc4;IfcOpenShell::geometry_serializer_ifc4x3_add2;IfcOpenShell::IfcParse"
)

# Create imported target IfcOpenShell::geometry_serializer_ifc2x3
add_library(IfcOpenShell::geometry_serializer_ifc2x3 INTERFACE IMPORTED)

set_target_properties(IfcOpenShell::geometry_serializer_ifc2x3 PROPERTIES
  INTERFACE_LINK_LIBRARIES "IfcOpenShell::OpenCASCADE_INTERFACE"
)

# Create imported target IfcOpenShell::geometry_serializer_ifc4
add_library(IfcOpenShell::geometry_serializer_ifc4 INTERFACE IMPORTED)

set_target_properties(IfcOpenShell::geometry_serializer_ifc4 PROPERTIES
  INTERFACE_LINK_LIBRARIES "IfcOpenShell::OpenCASCADE_INTERFACE"
)

# Create imported target IfcOpenShell::geometry_serializer_ifc4x3_add2
add_library(IfcOpenShell::geometry_serializer_ifc4x3_add2 INTERFACE IMPORTED)

set_target_properties(IfcOpenShell::geometry_serializer_ifc4x3_add2 PROPERTIES
  INTERFACE_LINK_LIBRARIES "IfcOpenShell::OpenCASCADE_INTERFACE"
)

# Create imported target IfcOpenShell::geometry_mapping_ifc2x3
add_library(IfcOpenShell::geometry_mapping_ifc2x3 INTERFACE IMPORTED)

set_target_properties(IfcOpenShell::geometry_mapping_ifc2x3 PROPERTIES
  INTERFACE_LINK_LIBRARIES "IfcOpenShell::IfcParse;Eigen3::Eigen"
)

# Create imported target IfcOpenShell::geometry_mapping_ifc4
add_library(IfcOpenShell::geometry_mapping_ifc4 INTERFACE IMPORTED)

set_target_properties(IfcOpenShell::geometry_mapping_ifc4 PROPERTIES
  INTERFACE_LINK_LIBRARIES "IfcOpenShell::IfcParse;Eigen3::Eigen"
)

# Create imported target IfcOpenShell::geometry_mapping_ifc4x3_add2
add_library(IfcOpenShell::geometry_mapping_ifc4x3_add2 INTERFACE IMPORTED)

set_target_properties(IfcOpenShell::geometry_mapping_ifc4x3_add2 PROPERTIES
  INTERFACE_LINK_LIBRARIES "IfcOpenShell::IfcParse;Eigen3::Eigen"
)

# Create imported target IfcOpenShell::IfcGeom
add_library(IfcOpenShell::IfcGeom SHARED IMPORTED)

set_target_properties(IfcOpenShell::IfcGeom PROPERTIES
  INTERFACE_LINK_LIBRARIES "IfcOpenShell::geometry_mapping_ifc2x3;IfcOpenShell::geometry_mapping_ifc4;IfcOpenShell::geometry_mapping_ifc4x3_add2;Eigen3::Eigen;IfcOpenShell::OpenCASCADE_INTERFACE;IfcOpenShell::IfcParse"
)

# Create imported target IfcOpenShell::IfcConvert
add_executable(IfcOpenShell::IfcConvert IMPORTED)

# Create imported target IfcOpenShell::IfcGeomServer
add_executable(IfcOpenShell::IfcGeomServer IMPORTED)

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/IfcOpenShellTargets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  if(CMAKE_VERSION VERSION_LESS "3.28"
      OR NOT DEFINED _cmake_import_check_xcframework_for_${_cmake_target}
      OR NOT IS_DIRECTORY "${_cmake_import_check_xcframework_for_${_cmake_target}}")
    foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
      if(NOT EXISTS "${_cmake_file}")
        message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
      endif()
    endforeach()
  endif()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
